"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lwy$%!md__me1&kw500(e8xc0pad5(fi8ge9b!x(lzf_j1vqv!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

PROVIDER_WEBHOOK_SECRET = os.environ.get("PROVIDER_WEBHOOK_SECRET", "")

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOG_DESTINATION = os.environ.get("LOG_DESTINATION", "console").lower()
LOG_FILE_PATH = os.environ.get("LOG_FILE_PATH", "logs/2remit.log")

VALID_LOG_LEVELS = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
VALID_LOG_DESTINATIONS = {"console", "file"}

if LOG_LEVEL not in VALID_LOG_LEVELS:
    raise ImproperlyConfigured(f"Unsupported LOG_LEVEL: {LOG_LEVEL}")

if LOG_DESTINATION not in VALID_LOG_DESTINATIONS:
    raise ImproperlyConfigured(
        f"Unsupported LOG_DESTINATION: {LOG_DESTINATION}"
    )

LOG_HANDLERS = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "json",
        "stream": "ext://sys.stderr",
    },
}
ACTIVE_LOG_HANDLERS = ["console"]

if LOG_DESTINATION == "file":
    resolved_log_path = Path(LOG_FILE_PATH)

    if not resolved_log_path.is_absolute():
        resolved_log_path = BASE_DIR / resolved_log_path

    resolved_log_path.parent.mkdir(parents=True, exist_ok=True)
    LOG_HANDLERS["file"] = {
        "class": "logging.FileHandler",
        "formatter": "json",
        "filename": str(resolved_log_path),
        "encoding": "utf-8",
    }
    ACTIVE_LOG_HANDLERS = ["file"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": (
                "%(asctime)s %(levelname)s %(name)s "
                "%(event)s %(message)s"
            ),
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
            "rename_fields": {
                "asctime": "timestamp",
                "levelname": "level",
                "name": "logger",
            },
        },
    },
    "handlers": LOG_HANDLERS,
    "root": {
        "handlers": ACTIVE_LOG_HANDLERS,
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ACTIVE_LOG_HANDLERS,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "transfers": {
            "handlers": ACTIVE_LOG_HANDLERS,
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'transfers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '2remit',
        'USER': 'oreoluwa',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
