# Generated by Django 5.2.17 on 2026-08-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('provider_transfer_id', models.CharField(db_index=True, max_length=255)),
                ('provider_status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_outcome', models.CharField(blank=True, choices=[('processed', 'Processed'), ('unknown_transfer', 'Unknown Transfer'), ('invalid_transition', 'Invalid Transition'), ('failed', 'Failed')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
